/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.produtos;

import bean.MpjTbProduto;
import dao.ProdutoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import view.produtos.JDlgProdutos;

/**
 *
 * @author u04584043221
 */
public class JDlgProdutosPesquisar extends javax.swing.JDialog {

    /**
     * Creates new form JDlgProdutosPesquisar
     */
    private ControllerProdutos controllerProdutos;
    JDlgProdutos jdlgProdutos;

    public JDlgProdutosPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        controllerProdutos = new ControllerProdutos();
        setLocationRelativeTo(null);
        jdlgProdutos = new JDlgProdutos();
        ProdutoDAO produtosDAO = new ProdutoDAO();
        List lstProdutos = (List) produtosDAO.listAll();

        mpj_jTbProdutos.setModel(controllerProdutos);
        controllerProdutos.setList(lstProdutos);

    }

    public void setTelaPai(JDlgProdutos jDlgProdutos) {
        this.jdlgProdutos = jDlgProdutos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mpj_jBtnOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mpj_JbtCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mpj_JSp = new javax.swing.JScrollPane();
        mpj_jTbProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mpj_jBtnOK.setText("OK");
        mpj_jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnOKActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productapplication_producto_3010.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Lista de Produtos");

        mpj_JbtCancelar.setText("Cancelar");
        mpj_JbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_JbtCancelarActionPerformed(evt);
            }
        });

        mpj_jTbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mpj_jTbProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mpj_jTbProdutosMouseClicked(evt);
            }
        });
        mpj_JSp.setViewportView(mpj_jTbProdutos);

        jScrollPane2.setViewportView(mpj_JSp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mpj_JbtCancelar)
                .addGap(18, 18, 18)
                .addComponent(mpj_jBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpj_jBtnOK)
                    .addComponent(mpj_JbtCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpj_jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnOKActionPerformed
        // TODO add your handling code here:
        int selectedRow = mpj_jTbProdutos.getSelectedRow();
        if (selectedRow != -1) {
            MpjTbProduto produtos = controllerProdutos.getBean(selectedRow);
            if (produtos != null) {
                jdlgProdutos.beanView(produtos);
            }
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um produto primeiro", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mpj_jBtnOKActionPerformed

    private void mpj_JbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_JbtCancelarActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_mpj_JbtCancelarActionPerformed

    private void mpj_jTbProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mpj_jTbProdutosMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 2) {
            mpj_jBtnOKActionPerformed(null);
        }
    }//GEN-LAST:event_mpj_jTbProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgProdutosPesquisar dialog = new JDlgProdutosPesquisar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane mpj_JSp;
    private javax.swing.JButton mpj_JbtCancelar;
    private javax.swing.JButton mpj_jBtnOK;
    private javax.swing.JTable mpj_jTbProdutos;
    // End of variables declaration//GEN-END:variables
}
