package view.produtos;

import bean.MpjTbProduto;
import dao.ProdutoDAO;
import funcionalidade.HistoricoTransacoes;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import tools.Util;
import view.Main;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author u04584043221
 */
public class JDlgProdutos extends javax.swing.JFrame {

    private boolean incluir = true;

    /**
     * Creates new form JDlgProdutos
     */
    public JDlgProdutos() {
        initComponents();
        Util.habilitar(false, mpj_jTxtIdProduto, mpj_jTxtNomeProduto, mpj_jFmtDataFabricacao, mpj_jTxtNomeFabricante, mpj_jFmtDataValidade, mpj_jTxtDescricao, mpj_jTxtSegmentoProduto, mpj_jTxtDescricao, mpj_jBtnConfirmar, mpj_jBtnCancelar);
    }

    public JDlgProdutos(Main aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public MpjTbProduto viewBeanProdutos() {
        MpjTbProduto produtos = new MpjTbProduto();
        produtos.setMpjNomeProduto(mpj_jTxtNomeProduto.getText());
        produtos.setMpjDescricaoProduto(mpj_jTxtDescricao.getText());
        produtos.setMpjNomeFabricante(mpj_jTxtNomeFabricante.getText());
        produtos.setMpjSegmentoProduto(mpj_jTxtSegmentoProduto.getText());
        produtos.setMpjPrecoProduto(Util.strToDouble(mpj_jTxtPrecoProduto.getText()));
        produtos.setMpjDataFabricaoProduto(Util.strToDate(mpj_jFmtDataFabricacao.getText()));
        if (Util.strToDate(mpj_jFmtDataValidade.getText()) == null) {
            Util.mensagem("Data Invalidada");
        } else {
            produtos.setMpjDataFabricaoProduto(Util.strToDate(mpj_jFmtDataFabricacao.getText()));
        }
        if (Util.strToDate(mpj_jFmtDataFabricacao.getText()) == null) {
            Util.mensagem("Data Invalidada");
        } else {
            produtos.setMpjValidadeProduto(Util.strToDate(mpj_jFmtDataValidade.getText()));
        }

        return produtos;

    }

    public void beanView(MpjTbProduto produtos) {
        mpj_jTxtIdProduto.setText(Util.intToStr(produtos.getMpjIdProduto()));
        mpj_jTxtNomeProduto.setText(produtos.getMpjNomeProduto());
        mpj_jTxtDescricao.setText(produtos.getMpjDescricaoProduto());
        mpj_jTxtNomeFabricante.setText(produtos.getMpjNomeFabricante());
        mpj_jTxtPrecoProduto.setText(Util.doubleToStr(produtos.getMpjPrecoProduto()));
        mpj_jTxtSegmentoProduto.setText(produtos.getMpjSegmentoProduto());
        mpj_jFmtDataFabricacao.setText(Util.dateToStr(produtos.getMpjDataFabricaoProduto()));
        mpj_jFmtDataValidade.setText(Util.dateToStr(produtos.getMpjValidadeProduto()));
    }

    public boolean validacaoProduto() {
        LineBorder bordaErro = new LineBorder(Color.RED, 2);
        LineBorder bordaNormal = new LineBorder(Color.GRAY, 1);

        // Nome do produto
        if (mpj_jTxtNomeProduto.getText().trim().length() <= 2) {
            Util.mensagem("Por favor, preencha o nome do produto corretamente.");
            mpj_jTxtNomeProduto.setBorder(bordaErro);
            return true;
        } else {
            mpj_jTxtNomeProduto.setBorder(bordaNormal);
        }

        // Descrição do produto
        if (mpj_jTxtDescricao.getText().trim().isEmpty()) {
            Util.mensagem("Por favor, preencha a descrição do produto.");
            mpj_jTxtDescricao.setBorder(bordaErro);
            return true;
        } else {
            mpj_jTxtDescricao.setBorder(bordaNormal);
        }

        // Fabricante
        if (mpj_jTxtNomeFabricante.getText().trim().isEmpty()) {
            Util.mensagem("Por favor, informe o nome do fabricante.");
            mpj_jTxtNomeFabricante.setBorder(bordaErro);
            return true;
        } else {
            mpj_jTxtNomeFabricante.setBorder(bordaNormal);
        }

        // Preço
        try {
            double preco = Util.strToDouble(mpj_jTxtPrecoProduto.getText());
            if (preco <= -1) {
                Util.mensagem("O preço do produto deve ser maior que zero.");
                mpj_jTxtPrecoProduto.setBorder(bordaErro);
                return true;
            } else {
                mpj_jTxtPrecoProduto.setBorder(bordaNormal);
            }
        } catch (NumberFormatException e) {
            Util.mensagem("Preço inválido. Digite apenas números.");
            mpj_jTxtPrecoProduto.setBorder(bordaErro);
            return true;
        }

        // Segmento
        if (mpj_jTxtSegmentoProduto.getText().trim().isEmpty()) {
            Util.mensagem("Por favor, informe o segmento do produto.");
            mpj_jTxtSegmentoProduto.setBorder(bordaErro);
            return true;
        } else {
            mpj_jTxtSegmentoProduto.setBorder(bordaNormal);
        }

        // Data de fabricação
        if (Util.strToDate(mpj_jFmtDataFabricacao.getText()) == null) {
            Util.mensagem("Data de fabricação inválida.");
            mpj_jFmtDataFabricacao.setBorder(bordaErro);
            return true;
        } else {
            mpj_jFmtDataFabricacao.setBorder(bordaNormal);
        }

        // Data de validade
        if (Util.strToDate(mpj_jFmtDataValidade.getText()) == null) {
            Util.mensagem("Data de validade inválida.");
            mpj_jFmtDataValidade.setBorder(bordaErro);
            return true;
        } else {
            mpj_jFmtDataValidade.setBorder(bordaNormal);
        }

        return false; // tudo válido
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        mpj_jTxtNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mpj_jTxtNomeFabricante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mpj_jTxtSegmentoProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mpj_jTxtDescricao = new javax.swing.JTextField();
        mpj_jBtnAlterar = new javax.swing.JButton();
        mpj_jBtnExcluir = new javax.swing.JButton();
        mpj_jBtnIncluir = new javax.swing.JButton();
        mpj_jBtnPesquisar = new javax.swing.JButton();
        mpj_jBtnConfirmar = new javax.swing.JButton();
        mpj_jBtnCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        mpj_jFmtDataValidade = new javax.swing.JFormattedTextField();
        mpj_jFmtDataFabricacao = new javax.swing.JFormattedTextField();
        mpj_jTxtPrecoProduto = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mpj_jTxtIdProduto = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Produtos");

        jLabel1.setText("Nome do Produto");

        mpj_jTxtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jTxtNomeProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de Fabricação");

        jLabel3.setText("Nome do Fabricante");

        jLabel4.setText("Segmento do Produto");

        jLabel5.setText("Data de Validade");

        jLabel6.setText("Descrição do Produto");

        mpj_jTxtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jTxtDescricaoActionPerformed(evt);
            }
        });

        mpj_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        mpj_jBtnAlterar.setText("Alterar");
        mpj_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnAlterarActionPerformed(evt);
            }
        });

        mpj_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_remove.png"))); // NOI18N
        mpj_jBtnExcluir.setText("Excluir");
        mpj_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnExcluirActionPerformed(evt);
            }
        });

        mpj_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_add.png"))); // NOI18N
        mpj_jBtnIncluir.setText("Incluir");
        mpj_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnIncluirActionPerformed(evt);
            }
        });

        mpj_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        mpj_jBtnPesquisar.setText("Pesquisar");
        mpj_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnPesquisarActionPerformed(evt);
            }
        });

        mpj_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apply.png"))); // NOI18N
        mpj_jBtnConfirmar.setText("Confirmar");
        mpj_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnConfirmarActionPerformed(evt);
            }
        });

        mpj_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        mpj_jBtnCancelar.setText("Cancelar");
        mpj_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productapplication_producto_3010.png"))); // NOI18N

        try {
            mpj_jFmtDataValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            mpj_jFmtDataFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        mpj_jTxtPrecoProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        mpj_jTxtPrecoProduto.setEnabled(false);

        jLabel8.setText("Preço Produto");

        jLabel9.setText("ID Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mpj_jTxtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(mpj_jBtnIncluir)
                                .addGap(33, 33, 33)
                                .addComponent(mpj_jBtnAlterar)
                                .addGap(18, 18, 18)
                                .addComponent(mpj_jBtnExcluir)
                                .addGap(16, 16, 16)
                                .addComponent(mpj_jBtnConfirmar)
                                .addGap(18, 18, 18)
                                .addComponent(mpj_jBtnCancelar)
                                .addGap(32, 32, 32)
                                .addComponent(mpj_jBtnPesquisar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2)
                                            .addComponent(mpj_jFmtDataFabricacao)
                                            .addComponent(jLabel5)
                                            .addComponent(mpj_jFmtDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(117, 117, 117)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel4)
                                                    .addComponent(mpj_jTxtSegmentoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 199, Short.MAX_VALUE))
                                            .addComponent(mpj_jTxtDescricao)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(mpj_jTxtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(mpj_jTxtNomeProduto)
                                        .addComponent(jLabel1)
                                        .addComponent(mpj_jTxtNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mpj_jTxtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mpj_jTxtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpj_jTxtNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mpj_jTxtSegmentoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mpj_jFmtDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mpj_jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mpj_jFmtDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpj_jTxtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpj_jBtnAlterar)
                    .addComponent(mpj_jBtnExcluir)
                    .addComponent(mpj_jBtnPesquisar)
                    .addComponent(mpj_jBtnIncluir)
                    .addComponent(mpj_jBtnConfirmar)
                    .addComponent(mpj_jBtnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpj_jTxtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jTxtNomeProdutoActionPerformed

    }//GEN-LAST:event_mpj_jTxtNomeProdutoActionPerformed

    private void mpj_jTxtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jTxtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpj_jTxtDescricaoActionPerformed

    private void mpj_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        Util.habilitar(true, mpj_jTxtNomeProduto, mpj_jFmtDataValidade, mpj_jTxtNomeFabricante, mpj_jFmtDataFabricacao, mpj_jTxtDescricao, mpj_jTxtSegmentoProduto, mpj_jTxtDescricao, mpj_jBtnConfirmar, mpj_jBtnCancelar, mpj_jTxtPrecoProduto);
        Util.habilitar(false, mpj_jTxtIdProduto, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
    }//GEN-LAST:event_mpj_jBtnAlterarActionPerformed

    private void mpj_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        ProdutoDAO produtoDAO = new ProdutoDAO();
        if (Util.perguntar("Deseja excluir o registro?") == true) {

            produtoDAO.delete(viewBeanProdutos());
            Util.mensagem("Produto deletado ");
            HistoricoTransacoes.salvar("DELETE PRODUTO", "ID PRODUTO" + viewBeanProdutos().getMpjIdProduto() + "Nome Produto" + viewBeanProdutos().getMpjNomeProduto());

        } else {
            Util.mensagem("Operacao Cancelada");

        }
    }//GEN-LAST:event_mpj_jBtnExcluirActionPerformed

    private void mpj_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mpj_jTxtNomeProduto, mpj_jFmtDataValidade, mpj_jTxtNomeFabricante, mpj_jFmtDataFabricacao, mpj_jTxtDescricao, mpj_jTxtSegmentoProduto, mpj_jTxtDescricao, mpj_jBtnConfirmar, mpj_jBtnCancelar, mpj_jTxtPrecoProduto);
        Util.habilitar(false, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
        incluir = true;
    }//GEN-LAST:event_mpj_jBtnIncluirActionPerformed

    private void mpj_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgProdutosPesquisar jdlgProdutosPesquisar = new JDlgProdutosPesquisar(null, true);
        jdlgProdutosPesquisar.setTelaPai(this);
        jdlgProdutosPesquisar.setVisible(true);
    }//GEN-LAST:event_mpj_jBtnPesquisarActionPerformed

    private void mpj_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        ProdutoDAO produtosDAO = new ProdutoDAO();
        if (validacaoProduto() == false) {
            if (incluir == true) {
                produtosDAO.insert(viewBeanProdutos());
                Util.mensagem("Produto cadastrado com sucesso ");
                HistoricoTransacoes.salvar("CREATE PRODUTO", "ID PRODUTO" + viewBeanProdutos().getMpjIdProduto() + "Nome Produto" + viewBeanProdutos().getMpjNomeProduto());

            } else {
                produtosDAO.update(viewBeanProdutos());
                Util.mensagem("Produto editado  com sucesso ");
                HistoricoTransacoes.salvar("UPDATE PRODUTO", "ID PRODUTO" + viewBeanProdutos().getMpjIdProduto() + "Nome Produto" + viewBeanProdutos().getMpjNomeProduto());

            }
            Util.limpar(mpj_jTxtIdProduto, mpj_jTxtPrecoProduto, mpj_jTxtNomeProduto, mpj_jFmtDataFabricacao, mpj_jTxtNomeFabricante, mpj_jFmtDataValidade, mpj_jTxtDescricao, mpj_jTxtSegmentoProduto, mpj_jTxtDescricao);

        }
    }//GEN-LAST:event_mpj_jBtnConfirmarActionPerformed

    private void mpj_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnCancelarActionPerformed
        // TODO add your handling code here:

        Util.habilitar(false, mpj_jTxtIdProduto, mpj_jTxtPrecoProduto, mpj_jTxtNomeProduto, mpj_jFmtDataFabricacao, mpj_jTxtNomeFabricante, mpj_jFmtDataValidade, mpj_jTxtDescricao, mpj_jTxtSegmentoProduto, mpj_jTxtDescricao);
        Util.habilitar(true, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
        Util.mensagem("Opercao Cancelada");
        Util.limpar(mpj_jTxtIdProduto, mpj_jTxtNomeProduto, mpj_jFmtDataFabricacao, mpj_jTxtNomeFabricante, mpj_jFmtDataValidade, mpj_jTxtDescricao, mpj_jTxtSegmentoProduto, mpj_jTxtDescricao);
    }//GEN-LAST:event_mpj_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDlgProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton mpj_jBtnAlterar;
    private javax.swing.JButton mpj_jBtnCancelar;
    private javax.swing.JButton mpj_jBtnConfirmar;
    private javax.swing.JButton mpj_jBtnExcluir;
    private javax.swing.JButton mpj_jBtnIncluir;
    private javax.swing.JButton mpj_jBtnPesquisar;
    private javax.swing.JFormattedTextField mpj_jFmtDataFabricacao;
    private javax.swing.JFormattedTextField mpj_jFmtDataValidade;
    private javax.swing.JTextField mpj_jTxtDescricao;
    private javax.swing.JTextField mpj_jTxtIdProduto;
    private javax.swing.JTextField mpj_jTxtNomeFabricante;
    private javax.swing.JTextField mpj_jTxtNomeProduto;
    private javax.swing.JFormattedTextField mpj_jTxtPrecoProduto;
    private javax.swing.JTextField mpj_jTxtSegmentoProduto;
    // End of variables declaration//GEN-END:variables
}
