/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import tools.Util;

/**
 *
 * @author u10916731103
 */
public class JDlgUsuarios extends javax.swing.JDialog {

    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários");
        setLocationRelativeTo(null);

        Util.habilitar(false, mpj_jTxtCodigo, mpj_jTxtNome, mpj_jTxtApelido,
                mpj_jFmtCpf, mpj_jFmtDataDeNascimento, mpj_jPwfSenha,
                mpj_jCboNivel, mpj_jChbAtivo, mpj_jBtnConfirmar, mpj_jBtnCancelar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mpj_jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mpj_jTxtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mpj_jTxtApelido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mpj_jFmtCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        mpj_jFmtDataDeNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        mpj_jPwfSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        mpj_jChbAtivo = new javax.swing.JCheckBox();
        mpj_jCboNivel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        mpj_jBtnIncluir = new javax.swing.JButton();
        mpj_jBtnAlterar = new javax.swing.JButton();
        mpj_jBtnExcluir = new javax.swing.JButton();
        mpj_jBtnConfirmar = new javax.swing.JButton();
        mpj_jBtnCancelar = new javax.swing.JButton();
        mpj_jBtnPesquisar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Usuários");
        setIconImage(null);

        jLabel1.setText("Código");

        mpj_jTxtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mpj_jTxtCodigoFocusLost(evt);
            }
        });

        jLabel2.setText("Nome");

        mpj_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jTxtNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Apelido");

        jLabel4.setText("CPF");

        mpj_jFmtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jFmtCpfActionPerformed(evt);
            }
        });

        jLabel5.setText("Data de Nascimento");

        mpj_jFmtDataDeNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jFmtDataDeNascimentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Senha");

        jLabel7.setText("Nível");

        mpj_jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "funcionario", "vendedor", "gerente" }));
        mpj_jCboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jCboNivelActionPerformed(evt);
            }
        });

        jLabel8.setText("Ativo");

        mpj_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_add.png"))); // NOI18N
        mpj_jBtnIncluir.setText("Incluir");
        mpj_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnIncluirActionPerformed(evt);
            }
        });

        mpj_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        mpj_jBtnAlterar.setText("Alterar");
        mpj_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnAlterarActionPerformed(evt);
            }
        });

        mpj_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_remove.png"))); // NOI18N
        mpj_jBtnExcluir.setText("Excluir");
        mpj_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnExcluirActionPerformed(evt);
            }
        });

        mpj_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        mpj_jBtnConfirmar.setText("Confirmar");
        mpj_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnConfirmarActionPerformed(evt);
            }
        });

        mpj_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        mpj_jBtnCancelar.setText("Cancelar");
        mpj_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnCancelarActionPerformed(evt);
            }
        });

        mpj_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        mpj_jBtnPesquisar.setText("Pesquisar");
        mpj_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user72.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Dados do Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mpj_jTxtNome)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(mpj_jPwfSenha)
                                                            .addComponent(mpj_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel6))
                                                    .addGap(75, 75, 75)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel7)
                                                        .addComponent(mpj_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGap(16, 16, 16)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(mpj_jFmtDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(94, 94, 94)
                                                    .addComponent(mpj_jChbAtivo)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel8))))
                                        .addComponent(mpj_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mpj_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(246, 246, 246)
                                .addComponent(jLabel12)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)))
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(mpj_jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpj_jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpj_jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpj_jBtnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpj_jBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpj_jBtnPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(mpj_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpj_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mpj_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpj_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpj_jFmtDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mpj_jChbAtivo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mpj_jPwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mpj_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpj_jBtnIncluir)
                    .addComponent(mpj_jBtnAlterar)
                    .addComponent(mpj_jBtnExcluir)
                    .addComponent(mpj_jBtnConfirmar)
                    .addComponent(mpj_jBtnCancelar)
                    .addComponent(mpj_jBtnPesquisar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpj_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpj_jTxtNomeActionPerformed

    private void mpj_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mpj_jTxtCodigo, mpj_jTxtNome, mpj_jTxtApelido,
                mpj_jFmtCpf, mpj_jFmtDataDeNascimento, mpj_jPwfSenha,
                mpj_jCboNivel, mpj_jChbAtivo, mpj_jBtnConfirmar, mpj_jBtnCancelar);
        Util.habilitar(false, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
        Util.limpar(mpj_jTxtCodigo, mpj_jTxtNome, mpj_jTxtApelido, mpj_jCboNivel);
    }//GEN-LAST:event_mpj_jBtnIncluirActionPerformed

    private void mpj_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mpj_jTxtNome, mpj_jTxtApelido,
                mpj_jFmtCpf, mpj_jFmtDataDeNascimento, mpj_jPwfSenha,
                mpj_jCboNivel, mpj_jChbAtivo, mpj_jBtnConfirmar, mpj_jBtnCancelar);
        Util.habilitar(false, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);

    }//GEN-LAST:event_mpj_jBtnAlterarActionPerformed

    private void mpj_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnExcluirActionPerformed
        // TODO add your handling code here:

        Util.perguntar("Deseja excluir o registro?");

    }//GEN-LAST:event_mpj_jBtnExcluirActionPerformed


    private void mpj_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, mpj_jTxtCodigo, mpj_jTxtNome, mpj_jTxtApelido,
                mpj_jFmtCpf, mpj_jFmtDataDeNascimento, mpj_jPwfSenha,
                mpj_jCboNivel, mpj_jChbAtivo, mpj_jBtnConfirmar, mpj_jBtnCancelar);
        Util.habilitar(true, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
            
    }//GEN-LAST:event_mpj_jBtnConfirmarActionPerformed

    private void mpj_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnPesquisarActionPerformed
     JDlgUsuariosPesquisar jdlgUsuariosPesquisar = new JDlgUsuariosPesquisar(null,true);
       jdlgUsuariosPesquisar.setTelaPai(this);
       jdlgUsuariosPesquisar.setVisible(true);

    }//GEN-LAST:event_mpj_jBtnPesquisarActionPerformed

    private void mpj_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, mpj_jTxtCodigo, mpj_jTxtNome, mpj_jTxtApelido,
                mpj_jFmtCpf, mpj_jFmtDataDeNascimento, mpj_jPwfSenha,
                mpj_jCboNivel, mpj_jChbAtivo, mpj_jBtnConfirmar, mpj_jBtnCancelar);
        Util.habilitar(true, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
        Util.limpar(mpj_jTxtCodigo, mpj_jTxtNome, mpj_jTxtApelido,
                mpj_jFmtCpf,mpj_jPwfSenha,mpj_jFmtDataDeNascimento,mpj_jChbAtivo,mpj_jCboNivel);

    }//GEN-LAST:event_mpj_jBtnCancelarActionPerformed

    private void mpj_jTxtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mpj_jTxtCodigoFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_mpj_jTxtCodigoFocusLost

    private void mpj_jCboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jCboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpj_jCboNivelActionPerformed

    private void mpj_jFmtDataDeNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jFmtDataDeNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpj_jFmtDataDeNascimentoActionPerformed

    private void mpj_jFmtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jFmtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpj_jFmtCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton mpj_jBtnAlterar;
    private javax.swing.JButton mpj_jBtnCancelar;
    private javax.swing.JButton mpj_jBtnConfirmar;
    private javax.swing.JButton mpj_jBtnExcluir;
    private javax.swing.JButton mpj_jBtnIncluir;
    private javax.swing.JButton mpj_jBtnPesquisar;
    private javax.swing.JComboBox<String> mpj_jCboNivel;
    private javax.swing.JCheckBox mpj_jChbAtivo;
    private javax.swing.JFormattedTextField mpj_jFmtCpf;
    private javax.swing.JFormattedTextField mpj_jFmtDataDeNascimento;
    private javax.swing.JPasswordField mpj_jPwfSenha;
    private javax.swing.JTextField mpj_jTxtApelido;
    private javax.swing.JTextField mpj_jTxtCodigo;
    private javax.swing.JTextField mpj_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
