/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import tools.Util;

/**
 *
 * @author mario
 */
public class JDlgFornecedores extends javax.swing.JDialog {

    /**
     * Creates new form JdlFornecedor
     */
    public JDlgFornecedores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mpj_jFmtCnpjFornecedor = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        mpj_jTxtRazaoSocialFornecedor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mpj_jTxtNomeFantasiaFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mpj_jFmtDataCriacaoEmpresa = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        mpj_jCboPorteFornecedor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        mpj_jCboQuantidadeFuncionariosFornecedor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        mpj_jFmtTelefoneFornecedor = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        mpj_jTxtEmailFornecedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mpj_jFtmCepFornecedor = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        mpj_jTxtNumeroFornecedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mpj_jCboEstadoFornecedor = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        mpj_jTxtComplementoFornecedor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mpj_jTxtServicoPrestado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        mpj_jTxtNomeRepresentanteFornecedor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        mpj_jBtnAlterar = new javax.swing.JButton();
        mpj_jBtnExcluir = new javax.swing.JButton();
        mpj_jBtnConfirmar = new javax.swing.JButton();
        mpj_jBtnCancelar = new javax.swing.JButton();
        mpj_jBtnPesquisar = new javax.swing.JButton();
        mpj_jBtnIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("CNPJ:");

        jLabel2.setText("Razão Social:");

        jLabel3.setText("Nome Fantasia:");

        jLabel4.setText("Data de  fundação:");

        jLabel5.setText("Porte da Empresa:");

        mpj_jCboPorteFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(MEI) Microempreendedor Individual", "(ME) Microempresa", "(EPP) Empresa de Pequeno Porte", "Média Empresa", "Grande Empresa" }));

        jLabel6.setText("Quantidade de Funcionários: ");

        mpj_jCboQuantidadeFuncionariosFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "menos que 10", "mais que 20", "mais que 50", "mais de 100" }));

        jLabel7.setText("Telefone:");

        jLabel8.setText("Email:");

        jLabel9.setText("CEP:");

        jLabel10.setText("Número:");

        jLabel11.setText("Estado:");

        mpj_jCboEstadoFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel12.setText("Complemento:");

        jLabel13.setText("Serviço Prestado");

        jLabel14.setText("Nome do Representante Legal:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setText("Cadastro do Fornecedor");

        mpj_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        mpj_jBtnAlterar.setText("Alterar");
        mpj_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnAlterarActionPerformed(evt);
            }
        });

        mpj_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_remove.png"))); // NOI18N
        mpj_jBtnExcluir.setText("Excluir");
        mpj_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnExcluirActionPerformed(evt);
            }
        });

        mpj_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apply.png"))); // NOI18N
        mpj_jBtnConfirmar.setText("Confirmar");
        mpj_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnConfirmarActionPerformed(evt);
            }
        });

        mpj_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        mpj_jBtnCancelar.setText("Cancelar");
        mpj_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnCancelarActionPerformed(evt);
            }
        });

        mpj_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        mpj_jBtnPesquisar.setText("Pesquisar");
        mpj_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnPesquisarActionPerformed(evt);
            }
        });

        mpj_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_add.png"))); // NOI18N
        mpj_jBtnIncluir.setText("Incluir");
        mpj_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jBtnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mpj_jTxtServicoPrestado, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mpj_jTxtNomeFantasiaFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mpj_jTxtRazaoSocialFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mpj_jFmtCnpjFornecedor, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mpj_jCboPorteFornecedor, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                                        .addComponent(mpj_jFmtTelefoneFornecedor, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mpj_jTxtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(mpj_jFmtDataCriacaoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(mpj_jCboQuantidadeFuncionariosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(mpj_jTxtNomeRepresentanteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mpj_jFtmCepFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mpj_jTxtNumeroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(mpj_jTxtComplementoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(mpj_jCboEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(mpj_jBtnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(mpj_jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(mpj_jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(mpj_jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(mpj_jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(mpj_jBtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel15)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpj_jFmtCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpj_jTxtRazaoSocialFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpj_jTxtNomeFantasiaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpj_jCboPorteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpj_jFmtTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mpj_jFmtDataCriacaoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mpj_jTxtNomeRepresentanteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpj_jCboQuantidadeFuncionariosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mpj_jTxtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(mpj_jFtmCepFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mpj_jTxtComplementoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mpj_jCboEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mpj_jTxtNumeroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mpj_jTxtServicoPrestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpj_jBtnAlterar)
                    .addComponent(mpj_jBtnExcluir)
                    .addComponent(mpj_jBtnPesquisar)
                    .addComponent(mpj_jBtnIncluir)
                    .addComponent(mpj_jBtnConfirmar)
                    .addComponent(mpj_jBtnCancelar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpj_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mpj_jTxtServicoPrestado, mpj_jTxtRazaoSocialFornecedor, mpj_jTxtNumeroFornecedor, mpj_jTxtNomeFantasiaFornecedor, mpj_jTxtNomeRepresentanteFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtComplementoFornecedor, mpj_jFmtTelefoneFornecedor, mpj_jFmtDataCriacaoEmpresa, mpj_jFmtCnpjFornecedor, mpj_jFtmCepFornecedor, mpj_jCboQuantidadeFuncionariosFornecedor, mpj_jCboPorteFornecedor, mpj_jCboEstadoFornecedor, mpj_jBtnConfirmar, mpj_jBtnCancelar);
        Util.habilitar(false, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
    }//GEN-LAST:event_mpj_jBtnAlterarActionPerformed

    private void mpj_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        Util.perguntar("Deseja excluir o registro?");
    }//GEN-LAST:event_mpj_jBtnExcluirActionPerformed

    private void mpj_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, mpj_jTxtServicoPrestado, mpj_jTxtRazaoSocialFornecedor, mpj_jTxtNumeroFornecedor, mpj_jTxtNomeFantasiaFornecedor, mpj_jTxtNomeRepresentanteFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtComplementoFornecedor, mpj_jFmtTelefoneFornecedor, mpj_jFmtDataCriacaoEmpresa, mpj_jFmtCnpjFornecedor, mpj_jFtmCepFornecedor, mpj_jCboQuantidadeFuncionariosFornecedor, mpj_jCboPorteFornecedor, mpj_jCboEstadoFornecedor, mpj_jBtnConfirmar, mpj_jBtnCancelar);

        Util.habilitar(true, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
    }//GEN-LAST:event_mpj_jBtnConfirmarActionPerformed

    private void mpj_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnCancelarActionPerformed
        // TODO add your handling code here:

        Util.habilitar(false, mpj_jTxtServicoPrestado, mpj_jTxtRazaoSocialFornecedor, mpj_jTxtNumeroFornecedor, mpj_jTxtNomeFantasiaFornecedor, mpj_jTxtNomeRepresentanteFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtComplementoFornecedor, mpj_jFmtTelefoneFornecedor, mpj_jFmtDataCriacaoEmpresa, mpj_jFmtCnpjFornecedor, mpj_jFtmCepFornecedor, mpj_jCboQuantidadeFuncionariosFornecedor, mpj_jCboPorteFornecedor, mpj_jCboEstadoFornecedor, mpj_jBtnConfirmar, mpj_jBtnCancelar);
        Util.habilitar(true, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
        Util.limpar(mpj_jTxtServicoPrestado, mpj_jTxtRazaoSocialFornecedor, mpj_jTxtNumeroFornecedor, mpj_jTxtNomeFantasiaFornecedor, mpj_jTxtNomeRepresentanteFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtComplementoFornecedor, mpj_jFmtTelefoneFornecedor, mpj_jFmtDataCriacaoEmpresa, mpj_jFmtCnpjFornecedor, mpj_jFtmCepFornecedor, mpj_jCboQuantidadeFuncionariosFornecedor, mpj_jCboPorteFornecedor, mpj_jCboEstadoFornecedor, mpj_jBtnConfirmar, mpj_jBtnCancelar);

    }//GEN-LAST:event_mpj_jBtnCancelarActionPerformed

    private void mpj_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
         JDlgFornecedorPesquisar jdlgFornecedorPesquisar = new JDlgFornecedorPesquisar(null,true);
       jdlgFornecedorPesquisar.setTelaPai(this);
      jdlgFornecedorPesquisar.setVisible(true);
    }//GEN-LAST:event_mpj_jBtnPesquisarActionPerformed

    private void mpj_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, mpj_jTxtServicoPrestado, mpj_jTxtRazaoSocialFornecedor, mpj_jTxtNumeroFornecedor, mpj_jTxtNomeFantasiaFornecedor, mpj_jTxtNomeRepresentanteFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtComplementoFornecedor, mpj_jFmtTelefoneFornecedor, mpj_jFmtDataCriacaoEmpresa, mpj_jFmtCnpjFornecedor, mpj_jFtmCepFornecedor, mpj_jCboQuantidadeFuncionariosFornecedor, mpj_jCboPorteFornecedor, mpj_jCboEstadoFornecedor, mpj_jBtnConfirmar, mpj_jBtnCancelar);
        Util.habilitar(false, mpj_jBtnIncluir, mpj_jBtnAlterar, mpj_jBtnExcluir, mpj_jBtnPesquisar);
        Util.limpar(mpj_jTxtServicoPrestado, mpj_jTxtRazaoSocialFornecedor, mpj_jTxtNumeroFornecedor, mpj_jTxtNomeFantasiaFornecedor, mpj_jTxtNomeRepresentanteFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtEmailFornecedor, mpj_jTxtComplementoFornecedor, mpj_jFmtTelefoneFornecedor, mpj_jFmtDataCriacaoEmpresa, mpj_jFmtCnpjFornecedor, mpj_jFtmCepFornecedor, mpj_jCboQuantidadeFuncionariosFornecedor, mpj_jCboPorteFornecedor, mpj_jCboEstadoFornecedor);

    }//GEN-LAST:event_mpj_jBtnIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFornecedores dialog = new JDlgFornecedores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mpj_jBtnAlterar;
    private javax.swing.JButton mpj_jBtnCancelar;
    private javax.swing.JButton mpj_jBtnConfirmar;
    private javax.swing.JButton mpj_jBtnExcluir;
    private javax.swing.JButton mpj_jBtnIncluir;
    private javax.swing.JButton mpj_jBtnPesquisar;
    private javax.swing.JComboBox<String> mpj_jCboEstadoFornecedor;
    private javax.swing.JComboBox<String> mpj_jCboPorteFornecedor;
    private javax.swing.JComboBox<String> mpj_jCboQuantidadeFuncionariosFornecedor;
    private javax.swing.JFormattedTextField mpj_jFmtCnpjFornecedor;
    private javax.swing.JFormattedTextField mpj_jFmtDataCriacaoEmpresa;
    private javax.swing.JFormattedTextField mpj_jFmtTelefoneFornecedor;
    private javax.swing.JFormattedTextField mpj_jFtmCepFornecedor;
    private javax.swing.JTextField mpj_jTxtComplementoFornecedor;
    private javax.swing.JTextField mpj_jTxtEmailFornecedor;
    private javax.swing.JTextField mpj_jTxtNomeFantasiaFornecedor;
    private javax.swing.JTextField mpj_jTxtNomeRepresentanteFornecedor;
    private javax.swing.JTextField mpj_jTxtNumeroFornecedor;
    private javax.swing.JTextField mpj_jTxtRazaoSocialFornecedor;
    private javax.swing.JTextField mpj_jTxtServicoPrestado;
    // End of variables declaration//GEN-END:variables
}
