package view;

import javax.swing.JOptionPane;
import tools.Util;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author u04584043221
 */
public class JDlgProdutos extends javax.swing.JFrame {

    /**
     * Creates new form JDlgProdutos
     */
    public JDlgProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTXTNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTXTNomeFabricante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTXTSegmentoProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JTXTDescricao = new javax.swing.JTextField();
        JBTAlterar = new javax.swing.JButton();
        JBTExcluir = new javax.swing.JButton();
        JBTIncluir = new javax.swing.JButton();
        JBTPesquisar = new javax.swing.JButton();
        JBTConfirmar = new javax.swing.JButton();
        JBTCancelar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JTFDataValidade = new javax.swing.JFormattedTextField();
        JTFDataFabricacao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Produtos");

        jLabel1.setText("Nome do Produto");

        JTXTNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTNomeProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data de Fabricação");

        jLabel3.setText("Nome do Fabricante");

        jLabel4.setText("Segmento do Produto");

        jLabel5.setText("Data de Validade");

        jLabel6.setText("Descrição do Produto");

        JTXTDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTXTDescricaoActionPerformed(evt);
            }
        });

        JBTAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        JBTAlterar.setText("Alterar");
        JBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTAlterarActionPerformed(evt);
            }
        });

        JBTExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_remove.png"))); // NOI18N
        JBTExcluir.setText("Excluir");
        JBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTExcluirActionPerformed(evt);
            }
        });

        JBTIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_add.png"))); // NOI18N
        JBTIncluir.setText("Incluir");
        JBTIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTIncluirActionPerformed(evt);
            }
        });

        JBTPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        JBTPesquisar.setText("Pesquisar");
        JBTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTPesquisarActionPerformed(evt);
            }
        });

        JBTConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apply.png"))); // NOI18N
        JBTConfirmar.setText("Confirmar");
        JBTConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTConfirmarActionPerformed(evt);
            }
        });

        JBTCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        JBTCancelar1.setText("Cancelar");
        JBTCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTCancelar1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/productapplication_producto_3010.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(JTFDataFabricacao, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(JTFDataValidade))
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(JTXTSegmentoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JTXTDescricao))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBTIncluir)
                .addGap(15, 15, 15)
                .addComponent(JBTAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBTExcluir)
                .addGap(18, 18, 18)
                .addComponent(JBTConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBTCancelar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBTPesquisar)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(JTXTNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(JTXTNomeFabricante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTXTNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTXTNomeFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTXTSegmentoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTXTDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFDataValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTAlterar)
                    .addComponent(JBTExcluir)
                    .addComponent(JBTPesquisar)
                    .addComponent(JBTIncluir)
                    .addComponent(JBTConfirmar)
                    .addComponent(JBTCancelar1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTXTNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTNomeProdutoActionPerformed
        Util.habilitar(true, JTXTNomeProduto, JTFDataValidade, JTXTNomeFabricante, JTFDataValidade, JTXTDescricao, JTXTSegmentoProduto, JTXTDescricao);
        Util.habilitar(false, JBTIncluir, JBTAlterar, JBTExcluir, JBTPesquisar);
    }//GEN-LAST:event_JTXTNomeProdutoActionPerformed

    private void JTXTDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTXTDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTXTDescricaoActionPerformed

    private void JBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTAlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, JTXTNomeProduto, JTFDataValidade, JTXTNomeFabricante, JTFDataValidade, JTXTDescricao, JTXTSegmentoProduto, JTXTDescricao);
        Util.habilitar(false, JBTIncluir, JBTAlterar, JBTExcluir, JBTPesquisar);
    }//GEN-LAST:event_JBTAlterarActionPerformed

    private void JBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTExcluirActionPerformed

    private void JBTIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTIncluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBTIncluirActionPerformed

    private void JBTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTPesquisarActionPerformed
        // TODO add your handling code here:
        Util.mensagem("Não implementado ");
    }//GEN-LAST:event_JBTPesquisarActionPerformed

    private void JBTConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, JTXTNomeProduto, JTXTNomeFabricante,JTFDataFabricacao,JTFDataValidade, JTXTDescricao, JTXTSegmentoProduto, JTXTDescricao);
        Util.habilitar(false, JBTIncluir, JBTAlterar, JBTExcluir, JBTPesquisar);
    }//GEN-LAST:event_JBTConfirmarActionPerformed

    private void JBTCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTCancelar1ActionPerformed
        // TODO add your handling code here:

        Util.habilitar(false, JTXTNomeProduto,JTFDataFabricacao, JTXTNomeFabricante, JTFDataValidade, JTXTDescricao, JTXTSegmentoProduto, JTXTDescricao);
        Util.habilitar(true, JBTIncluir, JBTAlterar, JBTExcluir, JBTPesquisar);
        Util.limpar(JTXTNomeProduto, JTFDataFabricacao,JTXTNomeFabricante, JTFDataValidade, JTXTDescricao, JTXTSegmentoProduto, JTXTDescricao);
    }//GEN-LAST:event_JBTCancelar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDlgProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTAlterar;
    private javax.swing.JButton JBTCancelar1;
    private javax.swing.JButton JBTConfirmar;
    private javax.swing.JButton JBTExcluir;
    private javax.swing.JButton JBTIncluir;
    private javax.swing.JButton JBTPesquisar;
    private javax.swing.JFormattedTextField JTFDataFabricacao;
    private javax.swing.JFormattedTextField JTFDataValidade;
    private javax.swing.JTextField JTXTDescricao;
    private javax.swing.JTextField JTXTNomeFabricante;
    private javax.swing.JTextField JTXTNomeProduto;
    private javax.swing.JTextField JTXTSegmentoProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
