/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import view.compra.JDlgCompra;
import view.compra.JDlgComprasProdutos;
import view.fornecedor.JDlgFornecedorPesquisar;
import view.fornecedor.JDlgFornecedores;
import view.funcionario.JDlgFuncionarios;
import view.funcionario.JDlgFuncionariosPesquisar;
import view.produtos.JDlgProdutos;
import view.produtos.JDlgProdutosPesquisar;
import view.usuarios.JDlgUsuarios;
import view.usuarios.JDlgUsuariosPesquisar;

/**
 * p
 *
 * @author mario
 */
public class Main extends javax.swing.JFrame {

    private JDlgCompra jDlgCompra;
    private JDlgUsuarios jDlgUsuarios;
    private JDlgProdutos jDlgProdutos;
    private JDlgFuncionarios jDlgFuncionarios;
    private JDlgFornecedores jDlgFornecedor;
    private JDlgUsuariosPesquisar jDlgUsuariosPesquisar;
    private JDlgProdutosPesquisar jDlgProdutosPesquisar;
    private JDlgFuncionariosPesquisar jDlgFuncionariosPesquisar;
    private JDlgFornecedorPesquisar jDlgFornecedorPesquisar;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mpj_jMniProduto = new javax.swing.JMenuItem();
        mpj_jMniUsuarios = new javax.swing.JMenuItem();
        mpj_jMnuiFornecedor = new javax.swing.JMenuItem();
        mpj_jMniFuncionarios = new javax.swing.JMenuItem();
        mpj_jMniCompraProduto = new javax.swing.JMenu();
        mpj_jMniCompra = new javax.swing.JMenuItem();
        mpj_jMniComprasPesquisar = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setFont(new java.awt.Font("Unispace", 2, 24)); // NOI18N
        jLabel1.setText("Sistema de Compras ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jMenu4.setText("Cadastros");
        jMenu4.add(jSeparator1);

        mpj_jMniProduto.setText("Produtos");
        mpj_jMniProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jMniProdutoActionPerformed(evt);
            }
        });
        jMenu4.add(mpj_jMniProduto);

        mpj_jMniUsuarios.setText("Usuarios");
        mpj_jMniUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jMniUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(mpj_jMniUsuarios);

        mpj_jMnuiFornecedor.setText("Fornecedor");
        mpj_jMnuiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jMnuiFornecedorActionPerformed(evt);
            }
        });
        jMenu4.add(mpj_jMnuiFornecedor);

        mpj_jMniFuncionarios.setText("Funcionarios");
        mpj_jMniFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jMniFuncionariosActionPerformed(evt);
            }
        });
        jMenu4.add(mpj_jMniFuncionarios);

        jMenuBar2.add(jMenu4);

        mpj_jMniCompraProduto.setText(" Movimento");

        mpj_jMniCompra.setText("Compra ");
        mpj_jMniCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jMniCompraActionPerformed(evt);
            }
        });
        mpj_jMniCompraProduto.add(mpj_jMniCompra);

        mpj_jMniComprasPesquisar.setText("Compra Produto");
        mpj_jMniComprasPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpj_jMniComprasPesquisarActionPerformed(evt);
            }
        });
        mpj_jMniCompraProduto.add(mpj_jMniComprasPesquisar);

        jMenuBar2.add(mpj_jMniCompraProduto);

        jMenu1.setText("Relatorio");

        jMenuItem1.setText("Gerar Historico de transacoes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpj_jMniCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jMniCompraActionPerformed
        // TODO add your handling code here:
        JDlgCompra jDlgCompra = new JDlgCompra(this, true);
        jDlgCompra.setVisible(true);
        jDlgCompra.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Reexibe o Main quando o diálogo fechar
                setVisible(true);
            }
        });

    }//GEN-LAST:event_mpj_jMniCompraActionPerformed

    private void mpj_jMniComprasPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jMniComprasPesquisarActionPerformed
        // TODO add your handling code here
        JDlgComprasProdutos jDlgComprasProdutos = new JDlgComprasProdutos(this, true);
        jDlgComprasProdutos.setVisible(true);
        jDlgComprasProdutos.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Reexibe o Main quando o diálogo fechar
                setVisible(true);
            }
        });


    }//GEN-LAST:event_mpj_jMniComprasPesquisarActionPerformed

    private void mpj_jMniUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jMniUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(this, true);
        jDlgUsuarios.setVisible(true);

        jDlgUsuarios.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Reexibe o Main quando o diálogo fechar
                setVisible(true);
            }
        });
    }//GEN-LAST:event_mpj_jMniUsuariosActionPerformed

    private void mpj_jMniProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jMniProdutoActionPerformed
        // TODO add your handling code here:
        JDlgProdutos jDlgProdutos = new JDlgProdutos();
        jDlgProdutos.setDefaultCloseOperation(JDlgProdutos.DISPOSE_ON_CLOSE); // importante
        jDlgProdutos.setVisible(true);

        jDlgProdutos.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Reexibe o Main quando o JFrame de produtos for fechado
                setVisible(true);
            }
        });
    }//GEN-LAST:event_mpj_jMniProdutoActionPerformed

    private void mpj_jMniFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jMniFuncionariosActionPerformed
        // TODO add your handling code here:

        JDlgFuncionarios jDlgFuncionarios = new JDlgFuncionarios(this, true);
        jDlgFuncionarios.setVisible(true);
        jDlgFuncionarios.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Reexibe o Main quando o diálogo fechar
                setVisible(true);
            }
        });

    }//GEN-LAST:event_mpj_jMniFuncionariosActionPerformed

    private void mpj_jMnuiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpj_jMnuiFornecedorActionPerformed
        // TODO add your handling code here:
        JDlgFornecedores jDlgFornecedores = new JDlgFornecedores(this, true);
        jDlgFornecedores.setVisible(true);
        jDlgFornecedores.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                // Reexibe o Main quando o diálogo fechar
                setVisible(true);
            }
        });

    }//GEN-LAST:event_mpj_jMnuiFornecedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // Caminho do arquivo CSV
        String caminhoArquivo = "historico-transacoes/historico/historico_transacoes.csv";
        File arquivo = new File(caminhoArquivo);

        // Verifica se o arquivo existe
        if (!arquivo.exists()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "O arquivo de histórico não foi encontrado!",
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Tenta abrir o arquivo usando o aplicativo padrão do sistema
        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            try {
                desktop.open(arquivo);
            } catch (IOException ex) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Não foi possível abrir o arquivo: " + ex.getMessage(),
                        "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "A operação não é suportada pelo seu sistema.",
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mpj_jMniCompra;
    private javax.swing.JMenu mpj_jMniCompraProduto;
    private javax.swing.JMenu mpj_jMniComprasPesquisar;
    private javax.swing.JMenuItem mpj_jMniFuncionarios;
    private javax.swing.JMenuItem mpj_jMniProduto;
    private javax.swing.JMenuItem mpj_jMniUsuarios;
    private javax.swing.JMenuItem mpj_jMnuiFornecedor;
    // End of variables declaration//GEN-END:variables
}
