package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MpjTbCompraProdutoId generated by hbm2java
 */
@Embeddable
public class MpjTbCompraProdutoId  implements java.io.Serializable {


     private int mpjIdCompra;
     private int mpjIdProduto;

    public MpjTbCompraProdutoId() {
    }

    public MpjTbCompraProdutoId(int mpjIdCompra, int mpjIdProduto) {
       this.mpjIdCompra = mpjIdCompra;
       this.mpjIdProduto = mpjIdProduto;
    }
   


    @Column(name="mpj_idCompra", nullable=false)
    public int getMpjIdCompra() {
        return this.mpjIdCompra;
    }
    
    public void setMpjIdCompra(int mpjIdCompra) {
        this.mpjIdCompra = mpjIdCompra;
    }


    @Column(name="mpj_idProduto", nullable=false)
    public int getMpjIdProduto() {
        return this.mpjIdProduto;
    }
    
    public void setMpjIdProduto(int mpjIdProduto) {
        this.mpjIdProduto = mpjIdProduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MpjTbCompraProdutoId) ) return false;
		 MpjTbCompraProdutoId castOther = ( MpjTbCompraProdutoId ) other; 
         
		 return (this.getMpjIdCompra()==castOther.getMpjIdCompra())
 && (this.getMpjIdProduto()==castOther.getMpjIdProduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMpjIdCompra();
         result = 37 * result + this.getMpjIdProduto();
         return result;
   }   


}


