package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MpjTbUsuario generated by hbm2java
 */
@Entity
@Table(name="mpj_tbUsuario"
    ,catalog="db_mario_junior"
)
public class MpjTbUsuario  implements java.io.Serializable {


     private int mpjIdUsuario;
     private String mpjNomeUsuario;
     private String mpjApelidoUsuario;
     private int mpjCpfUsuario;
     private Date mpjDataNascimentoUsuario;
     private Boolean mpjAtivoUsuario;
     private String mpjNivelUsuario;
     private String mpjSenhaFuncionario;

    public MpjTbUsuario() {
    }

	
    public MpjTbUsuario(String mpjNomeUsuario, String mpjApelidoUsuario, int mpjCpfUsuario, Date mpjDataNascimentoUsuario) {
        this.mpjNomeUsuario = mpjNomeUsuario;
        this.mpjApelidoUsuario = mpjApelidoUsuario;
        this.mpjCpfUsuario = mpjCpfUsuario;
        this.mpjDataNascimentoUsuario = mpjDataNascimentoUsuario;
    }
    public MpjTbUsuario(String mpjNomeUsuario, String mpjApelidoUsuario, int mpjCpfUsuario, Date mpjDataNascimentoUsuario, Boolean mpjAtivoUsuario, String mpjNivelUsuario, String mpjSenhaFuncionario) {
       this.mpjNomeUsuario = mpjNomeUsuario;
       this.mpjApelidoUsuario = mpjApelidoUsuario;
       this.mpjCpfUsuario = mpjCpfUsuario;
       this.mpjDataNascimentoUsuario = mpjDataNascimentoUsuario;
       this.mpjAtivoUsuario = mpjAtivoUsuario;
       this.mpjNivelUsuario = mpjNivelUsuario;
       this.mpjSenhaFuncionario = mpjSenhaFuncionario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="mpj_idUsuario", unique=true, nullable=false)
    public int getMpjIdUsuario() {
        return this.mpjIdUsuario;
    }
    
    public void setMpjIdUsuario(int mpjIdUsuario) {
        this.mpjIdUsuario = mpjIdUsuario;
    }

    
    @Column(name="mpj_nomeUsuario", nullable=false, length=60)
    public String getMpjNomeUsuario() {
        return this.mpjNomeUsuario;
    }
    
    public void setMpjNomeUsuario(String mpjNomeUsuario) {
        this.mpjNomeUsuario = mpjNomeUsuario;
    }

    
    @Column(name="mpj_apelidoUsuario", nullable=false, length=40)
    public String getMpjApelidoUsuario() {
        return this.mpjApelidoUsuario;
    }
    
    public void setMpjApelidoUsuario(String mpjApelidoUsuario) {
        this.mpjApelidoUsuario = mpjApelidoUsuario;
    }

    
    @Column(name="mpj_cpfUsuario", nullable=false)
    public int getMpjCpfUsuario() {
        return this.mpjCpfUsuario;
    }
    
    public void setMpjCpfUsuario(int mpjCpfUsuario) {
        this.mpjCpfUsuario = mpjCpfUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="mpj_dataNascimentoUsuario", nullable=false, length=10)
    public Date getMpjDataNascimentoUsuario() {
        return this.mpjDataNascimentoUsuario;
    }
    
    public void setMpjDataNascimentoUsuario(Date mpjDataNascimentoUsuario) {
        this.mpjDataNascimentoUsuario = mpjDataNascimentoUsuario;
    }

    
    @Column(name="mpj_ativoUsuario")
    public Boolean getMpjAtivoUsuario() {
        return this.mpjAtivoUsuario;
    }
    
    public void setMpjAtivoUsuario(Boolean mpjAtivoUsuario) {
        this.mpjAtivoUsuario = mpjAtivoUsuario;
    }

    
    @Column(name="mpj_nivelUsuario", length=40)
    public String getMpjNivelUsuario() {
        return this.mpjNivelUsuario;
    }
    
    public void setMpjNivelUsuario(String mpjNivelUsuario) {
        this.mpjNivelUsuario = mpjNivelUsuario;
    }

    
    @Column(name="mpj_senhaFuncionario", length=70)
    public String getMpjSenhaFuncionario() {
        return this.mpjSenhaFuncionario;
    }
    
    public void setMpjSenhaFuncionario(String mpjSenhaFuncionario) {
        this.mpjSenhaFuncionario = mpjSenhaFuncionario;
    }




}


