package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MpjTbFornecedor generated by hbm2java
 */
@Entity
@Table(name = "mpj_tbFornecedor",
        catalog = "db_mario_junior"
)
public class MpjTbFornecedor implements java.io.Serializable {

    private String mpjCnpjFornecedor;
    private String mpjNomeFantasiaFornecedor;
    private String mpjRazaoSocialFornecedor;
    private Date mpjDataCriacaoFornecedor;
    private String mpjQuantidadeFuncionariosFornecedor;
    private String mpjSegmentoFornecedor;
    private String mpjTelefoneFornecedor;
    private String mpjEmailFornecedor;
    private String mpjCepFornecedor;
    private String mpjRuaFornecedor;
    private int mpjNumeroFornecedor;
    private String mpjEstadoFornecedor;
    private String mpjServicoPrestadoFornecedor;
    private String mpjNomeResponsavelFornecedor;
    private String mpjPorteFornecedor;
    private String mpjComplementoFornecedor;

    public MpjTbFornecedor() {
    }

    public MpjTbFornecedor(String mpjComplementoFornecedor, int mpjNumeroFornecedor, String mpjQuantidadeFuncionariosFornecedor, String mpjCnpjFornecedor, String mpjNomeFantasiaFornecedor, String mpjRazaoSocialFornecedor, String mpjTelefoneFornecedor, String mpjEmailFornecedor, String mpjCepFornecedor, String mpjRuaFornecedor, String mpjServicoPrestadoFornecedor, String mpjNomeResponsavelFornecedor) {
        this.mpjCnpjFornecedor = mpjCnpjFornecedor;
        this.mpjNomeFantasiaFornecedor = mpjNomeFantasiaFornecedor;
        this.mpjRazaoSocialFornecedor = mpjRazaoSocialFornecedor;
        this.mpjTelefoneFornecedor = mpjTelefoneFornecedor;
        this.mpjEmailFornecedor = mpjEmailFornecedor;
        this.mpjCepFornecedor = mpjCepFornecedor;
        this.mpjRuaFornecedor = mpjRuaFornecedor;
        this.mpjServicoPrestadoFornecedor = mpjServicoPrestadoFornecedor;
        this.mpjNomeResponsavelFornecedor = mpjNomeResponsavelFornecedor;
        this.mpjQuantidadeFuncionariosFornecedor = mpjQuantidadeFuncionariosFornecedor;
        this.mpjNumeroFornecedor = mpjNumeroFornecedor;
        this.mpjComplementoFornecedor = mpjComplementoFornecedor;
    }

    public MpjTbFornecedor(String mpjComplementoFornecedor, int mpjNumeroFornecedor, String mpjCnpjFornecedor, String mpjNomeFantasiaFornecedor, String mpjRazaoSocialFornecedor, Date mpjDataCriacaoFornecedor, double mpjCapitalFornecedor, String mpjQuantidadeFuncionariosFornecedor, String mpjSegmentoFornecedor, String mpjTelefoneFornecedor, String mpjEmailFornecedor, String mpjCepFornecedor, String mpjRuaFornecedor, String mpjEstadoFornecedor, String mpjPaisFornecedor, String mpjServicoPrestadoFornecedor, String mpjNomeResponsavelFornecedor) {
        this.mpjCnpjFornecedor = mpjCnpjFornecedor;
        this.mpjNomeFantasiaFornecedor = mpjNomeFantasiaFornecedor;
        this.mpjRazaoSocialFornecedor = mpjRazaoSocialFornecedor;
        this.mpjDataCriacaoFornecedor = mpjDataCriacaoFornecedor;
        this.mpjQuantidadeFuncionariosFornecedor = mpjQuantidadeFuncionariosFornecedor;
        this.mpjSegmentoFornecedor = mpjSegmentoFornecedor;
        this.mpjTelefoneFornecedor = mpjTelefoneFornecedor;
        this.mpjEmailFornecedor = mpjEmailFornecedor;
        this.mpjCepFornecedor = mpjCepFornecedor;
        this.mpjRuaFornecedor = mpjRuaFornecedor;
        this.mpjEstadoFornecedor = mpjEstadoFornecedor;
        this.mpjServicoPrestadoFornecedor = mpjServicoPrestadoFornecedor;
        this.mpjNomeResponsavelFornecedor = mpjNomeResponsavelFornecedor;
        this.mpjComplementoFornecedor = mpjComplementoFornecedor;
        this.mpjNumeroFornecedor = mpjNumeroFornecedor;

    }

    @Id

    @Column(name = "mpj_cnpjFornecedor", unique = true, nullable = false, length = 30)
    public String getMpjCnpjFornecedor() {
        return this.mpjCnpjFornecedor;
    }

    public void setMpjCnpjFornecedor(String mpjCnpjFornecedor) {
        this.mpjCnpjFornecedor = mpjCnpjFornecedor;
    }

    @Column(name = "mpj_nomeFantasiaFornecedor", nullable = false, length = 60)
    public String getMpjNomeFantasiaFornecedor() {
        return this.mpjNomeFantasiaFornecedor;
    }

    public void setMpjPorteFornecedor(String mpjPorteFornecedor) {
        this.mpjPorteFornecedor = mpjPorteFornecedor;
    }

    @Column(name = "mpj_porteFornecedor", nullable = false, length = 100)
    public String getMpjPorteFornecedor() {
        return this.mpjPorteFornecedor;
    }

    public void setMpjNomeFantasiaFornecedor(String mpjNomeFantasiaFornecedor) {
        this.mpjNomeFantasiaFornecedor = mpjNomeFantasiaFornecedor;
    }

    @Column(name = "mpj_razaoSocialFornecedor", nullable = false, length = 60)
    public String getMpjRazaoSocialFornecedor() {
        return this.mpjRazaoSocialFornecedor;
    }

    public void setMpjRazaoSocialFornecedor(String mpjRazaoSocialFornecedor) {
        this.mpjRazaoSocialFornecedor = mpjRazaoSocialFornecedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "mpj_dataCriacaoFornecedor", length = 10)
    public Date getMpjDataCriacaoFornecedor() {
        return this.mpjDataCriacaoFornecedor;
    }

    public void setMpjDataCriacaoFornecedor(Date mpjDataCriacaoFornecedor) {
        this.mpjDataCriacaoFornecedor = mpjDataCriacaoFornecedor;
    }

    @Column(name = "mpj_quantidadeFuncionariosFornecedor", length = 100)
    public String getMpjQuantidadeFuncionariosFornecedor() {
        return this.mpjQuantidadeFuncionariosFornecedor;
    }

    public void setMpjQuantidadeFuncionariosFornecedor(String mpjQuantidadeFuncionariosFornecedor) {
        this.mpjQuantidadeFuncionariosFornecedor = mpjQuantidadeFuncionariosFornecedor;
    }

    @Column(name = "mpj_segmentoFornecedor", length = 40)
    public String getMpjSegmentoFornecedor() {
        return this.mpjSegmentoFornecedor;
    }

    public void setMpjSegmentoFornecedor(String mpjSegmentoFornecedor) {
        this.mpjSegmentoFornecedor = mpjSegmentoFornecedor;
    }

    @Column(name = "mpj_telefoneFornecedor", nullable = false, length = 30)
    public String getMpjTelefoneFornecedor() {
        return this.mpjTelefoneFornecedor;
    }

    public void setMpjTelefoneFornecedor(String mpjTelefoneFornecedor) {
        this.mpjTelefoneFornecedor = mpjTelefoneFornecedor;
    }

    @Column(name = "mpj_emailFornecedor", nullable = false, length = 40)
    public String getMpjEmailFornecedor() {
        return this.mpjEmailFornecedor;
    }

    public void setMpjEmailFornecedor(String mpjEmailFornecedor) {
        this.mpjEmailFornecedor = mpjEmailFornecedor;
    }

    @Column(name = "mpj_cepFornecedor", nullable = false, length = 30)
    public String getMpjCepFornecedor() {
        return this.mpjCepFornecedor;
    }

    public void setMpjCepFornecedor(String mpjCepFornecedor) {
        this.mpjCepFornecedor = mpjCepFornecedor;
    }

    @Column(name = "mpj_ruaFornecedor", nullable = false, length = 200)
    public String getMpjRuaFornecedor() {
        return this.mpjRuaFornecedor;
    }

    public void setMpjRuaFornecedor(String mpjRuaFornecedor) {
        this.mpjRuaFornecedor = mpjRuaFornecedor;
    }

    @Column(name = "mpj_estadoFornecedor", length = 20)
    public String getMpjEstadoFornecedor() {
        return this.mpjEstadoFornecedor;
    }

    public void setMpjEstadoFornecedor(String mpjEstadoFornecedor) {
        this.mpjEstadoFornecedor = mpjEstadoFornecedor;
    }

    @Column(name = "mpj_servicoPrestadoFornecedor", nullable = false, length = 300)
    public String getMpjServicoPrestadoFornecedor() {
        return this.mpjServicoPrestadoFornecedor;
    }

    public void setMpjServicoPrestadoFornecedor(String mpjServicoPrestadoFornecedor) {
        this.mpjServicoPrestadoFornecedor = mpjServicoPrestadoFornecedor;
    }

    @Column(name = "mpj_nomeResponsavelFornecedor", nullable = false, length = 60)
    public String getMpjNomeResponsavelFornecedor() {
        return this.mpjNomeResponsavelFornecedor;
    }

    public void setMpjNomeResponsavelFornecedor(String mpjNomeResponsavelFornecedor) {
        this.mpjNomeResponsavelFornecedor = mpjNomeResponsavelFornecedor;
    }

    @Column(name = "numeroFornecedor", nullable = false)
    public int getMpjNumeroFornecedor() {
        return this.mpjNumeroFornecedor;
    }

    public void setMpjNumeroFornecedor(int mpjNumeroFornecedor) {
        this.mpjNumeroFornecedor = mpjNumeroFornecedor;
    }

    @Column(name = "complementoFornecedor", nullable = false, length = 200)
    public String getMpjComplementoFornecedor() {
        return this.mpjComplementoFornecedor;
    }

    public void setMpjComplementoFornecedor(String mpjComplementoFornecedor) {
        this.mpjComplementoFornecedor = mpjComplementoFornecedor;
    }

    @Override
    public String toString() {
        return mpjNomeFantasiaFornecedor + " - " + mpjCnpjFornecedor; //To change body of generated methods, choose Tools | Templates.
    }

}
