package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MpjTbCompraProdutoId generated by hbm2java
 */
@Embeddable
public class MpjTbCompraProdutoId  implements java.io.Serializable {


    public MpjTbCompraProdutoId() {
    }  
}


