package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MpjTbCompraProduto generated by hbm2java
 */
@Entity
@Table(name = "mpj_tbCompraProduto",
        catalog = "db_mario_junior"
)
public class MpjTbCompraProduto implements java.io.Serializable {

    private int mpj_idCompraProduto;
    private MpjTbCompra mpjTbCompra;
    private MpjTbProduto mpjTbProduto;
    private int mpjQuantidadeProduto;
    private double mpjValorUnitario;

    public MpjTbCompraProduto() {
    }

    public MpjTbCompraProduto(int mpj_idCompraProduto, MpjTbCompra mpjTbCompra, MpjTbProduto mpjTbProduto, int mpjQuantidadeProduto) {
        this.mpj_idCompraProduto = mpj_idCompraProduto;
        this.mpjTbCompra = mpjTbCompra;
        this.mpjTbProduto = mpjTbProduto;
        this.mpjQuantidadeProduto = mpjQuantidadeProduto;
    }

    public MpjTbCompraProduto(int mpj_idCompraProduto, MpjTbCompra mpjTbCompra, MpjTbProduto mpjTbProduto, int mpjQuantidadeProduto, double mpjValorUnitario) {
        this.mpj_idCompraProduto = mpj_idCompraProduto;
        this.mpjTbCompra = mpjTbCompra;
        this.mpjTbProduto = mpjTbProduto;
        this.mpjQuantidadeProduto = mpjQuantidadeProduto;
        this.mpjValorUnitario = mpjValorUnitario;
    }

    @Id
    @Column(name = "id_compra_produto")
    public int getmpj_idCompraProduto() {
        return this.mpj_idCompraProduto;
    }

    public void setmpj_idCompraProduto(int mpj_idCompraProduto) {
        this.mpj_idCompraProduto = mpj_idCompraProduto;
    }

    @ManyToOne(fetch = FetchType.
            EAGER)
    @JoinColumn(name = "mpj_idCompra", nullable = false)
    public MpjTbCompra getMpjTbCompra() {
        return this.mpjTbCompra;
    }

    public void setMpjTbCompra(MpjTbCompra mpjTbCompra) {
        this.mpjTbCompra = mpjTbCompra;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "mpj_idProduto", nullable = false)
    public MpjTbProduto getMpjTbProduto() {
        return this.mpjTbProduto;
    }

    public void setMpjTbProduto(MpjTbProduto mpjTbProduto) {
        this.mpjTbProduto = mpjTbProduto;
    }

    @Column(name = "mpj_quantidadeProduto", nullable = false)
    public int getMpjQuantidadeProduto() {
        return this.mpjQuantidadeProduto;
    }

    public void setMpjQuantidadeProduto(int mpjQuantidadeProduto) {
        this.mpjQuantidadeProduto = mpjQuantidadeProduto;
    }

    @Column(name = "mpj_valorUnitario", precision = 10)
    public double getMpjValorUnitario() {
        return this.mpjValorUnitario;
    }

    public void setMpjValorUnitario(double mpjValorUnitario) {
        this.mpjValorUnitario = mpjValorUnitario;
    }

}
