package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MpjTbCompra generated by hbm2java
 */
@Entity
@Table(name = "mpj_tbCompra",
        catalog = "db_mario_junior"
)
public class MpjTbCompra implements java.io.Serializable {

    private int mpjIdCompra;
    private MpjTbFornecedor mpjTbFornecedor;
    private MpjTbFuncionario mpjTbFuncionario;
    private Date mpjDataCompra;
    private double mpjValorCompra;

    public MpjTbCompra() {
    }

    public MpjTbCompra(Date mpjDataCompra) {
        this.mpjDataCompra = mpjDataCompra;
    }

    public MpjTbCompra(MpjTbFornecedor mpjTbFornecedor, MpjTbFuncionario mpjTbFuncionario, Date mpjDataCompra, double mpjValorCompra) {
        this.mpjTbFornecedor = mpjTbFornecedor;
        this.mpjTbFuncionario = mpjTbFuncionario;
        this.mpjDataCompra = mpjDataCompra;
        this.mpjValorCompra = mpjValorCompra;

    }

    @Id
 
    @Column(name = "mpj_idCompra", unique = true, nullable = false)
    public int getMpjIdCompra() {
        return this.mpjIdCompra;
    }

    public void setMpjIdCompra(int mpjIdCompra) {
        this.mpjIdCompra = mpjIdCompra;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "mpj_cnpjFornecedorCompra")
    public MpjTbFornecedor getMpjTbFornecedor() {
        return this.mpjTbFornecedor;
    }

    public void setMpjTbFornecedor(MpjTbFornecedor mpjTbFornecedor) {
        this.mpjTbFornecedor = mpjTbFornecedor;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "mpj_cpfFuncionarioCompra")
    public MpjTbFuncionario getMpjTbFuncionario() {
        return this.mpjTbFuncionario;
    }

    public void setMpjTbFuncionario(MpjTbFuncionario mpjTbFuncionario) {
        this.mpjTbFuncionario = mpjTbFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "mpj_dataCompra", nullable = false, length = 10)
    public Date getMpjDataCompra() {
        return this.mpjDataCompra;
    }

    public void setMpjDataCompra(Date mpjDataCompra) {
        this.mpjDataCompra = mpjDataCompra;
    }

    @Column(name = "mpj_valorCompra", precision = 10)
    public double getMpjValorCompra() {
        return this.mpjValorCompra;
    }

    public void setMpjValorCompra(double mpjValorCompra) {
        this.mpjValorCompra = mpjValorCompra;
    }

}
