package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1



import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MpjTbCompraProduto generated by hbm2java
 */
@Entity
@Table(name="mpj_tbCompraProduto"
    ,catalog="db_mario_junior"
)
public class MpjTbCompraProduto  implements java.io.Serializable {


     private MpjTbCompraProdutoId id;
     private MpjTbCompra mpjTbCompra;
     private MpjTbProduto mpjTbProduto;
     private int mpjQuantidadeProduto;
     private double  mpjValorUnitario;

    public MpjTbCompraProduto() {
    }

	
    public MpjTbCompraProduto(MpjTbCompraProdutoId id, MpjTbCompra mpjTbCompra, MpjTbProduto mpjTbProduto, int mpjQuantidadeProduto) {
        this.id = id;
        this.mpjTbCompra = mpjTbCompra;
        this.mpjTbProduto = mpjTbProduto;
        this.mpjQuantidadeProduto = mpjQuantidadeProduto;
    }
    public MpjTbCompraProduto(MpjTbCompraProdutoId id, MpjTbCompra mpjTbCompra, MpjTbProduto mpjTbProduto, int mpjQuantidadeProduto, double mpjValorUnitario) {
       this.id = id;
       this.mpjTbCompra = mpjTbCompra;
       this.mpjTbProduto = mpjTbProduto;
       this.mpjQuantidadeProduto = mpjQuantidadeProduto;
       this.mpjValorUnitario = mpjValorUnitario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="mpjIdCompra", column=@Column(name="mpj_idCompra", nullable=false) ), 
        @AttributeOverride(name="mpjIdProduto", column=@Column(name="mpj_idProduto", nullable=false) ) } )
    public MpjTbCompraProdutoId getId() {
        return this.id;
    }
    
    public void setId(MpjTbCompraProdutoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mpj_idCompra", nullable=false, insertable=false, updatable=false)
    public MpjTbCompra getMpjTbCompra() {
        return this.mpjTbCompra;
    }
    
    public void setMpjTbCompra(MpjTbCompra mpjTbCompra) {
        this.mpjTbCompra = mpjTbCompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mpj_idProduto", nullable=false, insertable=false, updatable=false)
    public MpjTbProduto getMpjTbProduto() {
        return this.mpjTbProduto;
    }
    
    public void setMpjTbProduto(MpjTbProduto mpjTbProduto) {
        this.mpjTbProduto = mpjTbProduto;
    }

    
    @Column(name="mpj_quantidadeProduto", nullable=false)
    public int getMpjQuantidadeProduto() {
        return this.mpjQuantidadeProduto;
    }
    
    public void setMpjQuantidadeProduto(int mpjQuantidadeProduto) {
        this.mpjQuantidadeProduto = mpjQuantidadeProduto;
    }

    
    @Column(name="mpj_valorUnitario", precision=10)
    public double getMpjValorUnitario() {
        return this.mpjValorUnitario;
    }
    
    public void setMpjValorUnitario(double mpjValorUnitario) {
        this.mpjValorUnitario = mpjValorUnitario;
    }




}


