package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MpjTbProduto generated by hbm2java
 */
@Entity
@Table(name = "mpj_tbProduto",
        catalog = "db_mario_junior"
)
public class MpjTbProduto implements java.io.Serializable {

    private int mpjIdProduto;
    private String mpjNomeProduto;
    private Date mpjDataFabricaoProduto;
    private String mpjNomeFabricante;
    private String mpjSegmentoProduto;
    private Date mpjValidadeProduto;
    private String mpjDescricaoProduto;
    private double mpjPrecoProduto;

    public MpjTbProduto() {
    }

    public MpjTbProduto(String mpjNomeProduto, Date mpjDataFabricaoProduto, String mpjNomeFabricante, Date mpjValidadeProduto) {
        this.mpjNomeProduto = mpjNomeProduto;
        this.mpjDataFabricaoProduto = mpjDataFabricaoProduto;
        this.mpjNomeFabricante = mpjNomeFabricante;
        this.mpjValidadeProduto = mpjValidadeProduto;
    }

    public MpjTbProduto(String mpjNomeProduto, Date mpjDataFabricaoProduto, String mpjNomeFabricante, String mpjSegmentoProduto, Date mpjValidadeProduto, String mpjDescricaoProduto, double mpjPrecoProduto) {
        this.mpjNomeProduto = mpjNomeProduto;
        this.mpjDataFabricaoProduto = mpjDataFabricaoProduto;
        this.mpjNomeFabricante = mpjNomeFabricante;
        this.mpjSegmentoProduto = mpjSegmentoProduto;
        this.mpjValidadeProduto = mpjValidadeProduto;
        this.mpjDescricaoProduto = mpjDescricaoProduto;
        this.mpjPrecoProduto = mpjPrecoProduto;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "mpj_idProduto", unique = true, nullable = false)
    public int getMpjIdProduto() {
        return this.mpjIdProduto;
    }

    public void setMpjIdProduto(int mpjIdProduto) {
        this.mpjIdProduto = mpjIdProduto;
    }

    @Column(name = "mpj_nomeProduto", nullable = false, length = 60)
    public String getMpjNomeProduto() {
        return this.mpjNomeProduto;
    }

    public void setMpjNomeProduto(String mpjNomeProduto) {
        this.mpjNomeProduto = mpjNomeProduto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "mpj_dataFabricaoProduto", nullable = false, length = 10)
    public Date getMpjDataFabricaoProduto() {
        return this.mpjDataFabricaoProduto;
    }

    public void setMpjDataFabricaoProduto(Date mpjDataFabricaoProduto) {
        this.mpjDataFabricaoProduto = mpjDataFabricaoProduto;
    }

    @Column(name = "mpj_nomeFabricante", nullable = false, length = 60)
    public String getMpjNomeFabricante() {
        return this.mpjNomeFabricante;
    }

    public void setMpjNomeFabricante(String mpjNomeFabricante) {
        this.mpjNomeFabricante = mpjNomeFabricante;
    }

    @Column(name = "mpj_segmentoProduto", length = 20)
    public String getMpjSegmentoProduto() {
        return this.mpjSegmentoProduto;
    }

    public void setMpjSegmentoProduto(String mpjSegmentoProduto) {
        this.mpjSegmentoProduto = mpjSegmentoProduto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "mpj_validadeProduto", nullable = false, length = 10)
    public Date getMpjValidadeProduto() {
        return this.mpjValidadeProduto;
    }

    public void setMpjValidadeProduto(Date mpjValidadeProduto) {
        this.mpjValidadeProduto = mpjValidadeProduto;
    }

    @Column(name = "mpj_descricaoProduto", length = 300)
    public String getMpjDescricaoProduto() {
        return this.mpjDescricaoProduto;
    }

    public void setMpjDescricaoProduto(String mpjDescricaoProduto) {
        this.mpjDescricaoProduto = mpjDescricaoProduto;
    }

    @Column(name = "mpj_precoProduto", precision = 10)
    public double getMpjPrecoProduto() {
        return this.mpjPrecoProduto;
    }

    public void setMpjPrecoProduto(double mpjPrecoProduto) {
        this.mpjPrecoProduto = mpjPrecoProduto;
    }

}
