package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MpjTbFuncionario generated by hbm2java
 */
@Entity
@Table(name = "mpj_tbFuncionario",
        catalog = "db_mario_junior"
)
public class MpjTbFuncionario implements java.io.Serializable {

    private String mpjCpfFuncionario;
    private String mpjNomeCompletoFuncionario;
    private String mpjTelefoneFuncionario;
    private String mpjEmailFuncionario;
    private String mpjCargoFuncionario;
    private String mpjSetorFuncionario;
    private String mpjSexoFuncionario;
    private Date mpjDataNascimento;

    public MpjTbFuncionario() {
    }

    public MpjTbFuncionario(String mpjCpfFuncionario, String mpjNomeCompletoFuncionario, String mpjSetorFuncionario, String mpjSexoFuncionario, Date mpjDataNascimento) {
        this.mpjCpfFuncionario = mpjCpfFuncionario;
        this.mpjNomeCompletoFuncionario = mpjNomeCompletoFuncionario;
        this.mpjSetorFuncionario = mpjSetorFuncionario;
        this.mpjSexoFuncionario = mpjSexoFuncionario;
        this.mpjDataNascimento = mpjDataNascimento;
    }

    public MpjTbFuncionario(String mpjCpfFuncionario, String mpjNomeCompletoFuncionario, String mpjTelefoneFuncionario, String mpjEmailFuncionario, String mpjCargoFuncionario, String mpjSetorFuncionario, String mpjSexoFuncionario, Date mpjDataNascimento) {
        this.mpjCpfFuncionario = mpjCpfFuncionario;
        this.mpjNomeCompletoFuncionario = mpjNomeCompletoFuncionario;
        this.mpjTelefoneFuncionario = mpjTelefoneFuncionario;
        this.mpjEmailFuncionario = mpjEmailFuncionario;
        this.mpjCargoFuncionario = mpjCargoFuncionario;
        this.mpjSetorFuncionario = mpjSetorFuncionario;
        this.mpjSexoFuncionario = mpjSexoFuncionario;
        this.mpjDataNascimento = mpjDataNascimento;

    }

    @Id

    @Column(name = "mpj_cpfFuncionario", unique = true, nullable = false)
    public String getMpjCpfFuncionario() {
        return this.mpjCpfFuncionario;
    }

    public void setMpjCpfFuncionario(String  mpjCpfFuncionario) {
        this.mpjCpfFuncionario = mpjCpfFuncionario;
    }

    @Column(name = "mpj_nomeCompletoFuncionario", nullable = false, length = 200)
    public String getMpjNomeCompletoFuncionario() {
        return this.mpjNomeCompletoFuncionario;
    }

    public void setMpjNomeCompletoFuncionario(String mpjNomeCompletoFuncionario) {
        this.mpjNomeCompletoFuncionario = mpjNomeCompletoFuncionario;
    }

    @Column(name = "mpj_telefoneFuncionario", length = 60)
    public String getMpjTelefoneFuncionario() {
        return this.mpjTelefoneFuncionario;
    }

    public void setMpjTelefoneFuncionario(String mpjTelefoneFuncionario) {
        this.mpjTelefoneFuncionario = mpjTelefoneFuncionario;
    }

    @Column(name = "mpj_emailFuncionario", length = 60)
    public String getMpjEmailFuncionario() {
        return this.mpjEmailFuncionario;
    }

    public void setMpjEmailFuncionario(String mpjEmailFuncionario) {
        this.mpjEmailFuncionario = mpjEmailFuncionario;
    }

    @Column(name = "mpj_cargoFuncionario", length = 60)
    public String getMpjCargoFuncionario() {
        return this.mpjCargoFuncionario;
    }

    public void setMpjCargoFuncionario(String mpjCargoFuncionario) {
        this.mpjCargoFuncionario = mpjCargoFuncionario;
    }

    @Column(name = "mpj_setorFuncionario", nullable = false, length = 40)
    public String getMpjSetorFuncionario() {
        return this.mpjSetorFuncionario;
    }

    public void setMpjSetorFuncionario(String mpjSetorFuncionario) {
        this.mpjSetorFuncionario = mpjSetorFuncionario;
    }

    @Column(name = "mpj_sexoFuncionario", nullable = false, length = 20)
    public String getMpjSexoFuncionario() {
        return this.mpjSexoFuncionario;
    }

    public void setMpjSexoFuncionario(String mpjSexoFuncionario) {
        this.mpjSexoFuncionario = mpjSexoFuncionario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "mpj_dataNascimentoFuncionario", nullable = false, length = 10)
    public Date getMpjDataNascimento() {
        return this.mpjDataNascimento;
    }
    
    @Override
    public String toString() {
    return mpjNomeCompletoFuncionario + " - " + mpjCargoFuncionario;
}

    public void setMpjDataNascimento(Date mpjDataNascimento) {
        this.mpjDataNascimento = mpjDataNascimento;
    }

}
