package bean;
// Generated 08/10/2025 12:07:45 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MpjTbFuncionario generated by hbm2java
 */
@Entity
@Table(name = "mpj_tbFuncionario",
         catalog = "db_mario_junior"
)
public class MpjTbFuncionario implements java.io.Serializable {

    private int mpjCpfFuncionario;
    private String mpjNomeCompletoFuncionario;
    private String mpjTelefoneFuncionario;
    private String mpjEmailFuncionario;
    private String mpjCargoFuncionario;
    private String mpjSetorFuncionario;
    private String mpjSexoFuncionario;

    public MpjTbFuncionario() {
    }

    public MpjTbFuncionario(int mpjCpfFuncionario, String mpjNomeCompletoFuncionario, String mpjSetorFuncionario, String mpjSexoFuncionario) {
        this.mpjCpfFuncionario = mpjCpfFuncionario;
        this.mpjNomeCompletoFuncionario = mpjNomeCompletoFuncionario;
        this.mpjSetorFuncionario = mpjSetorFuncionario;
        this.mpjSexoFuncionario = mpjSexoFuncionario;
    }

    public MpjTbFuncionario(int mpjCpfFuncionario, String mpjNomeCompletoFuncionario, String mpjTelefoneFuncionario, String mpjEmailFuncionario, String mpjCargoFuncionario, String mpjSetorFuncionario, String mpjSexoFuncionario) {
        this.mpjCpfFuncionario = mpjCpfFuncionario;
        this.mpjNomeCompletoFuncionario = mpjNomeCompletoFuncionario;
        this.mpjTelefoneFuncionario = mpjTelefoneFuncionario;
        this.mpjEmailFuncionario = mpjEmailFuncionario;
        this.mpjCargoFuncionario = mpjCargoFuncionario;
        this.mpjSetorFuncionario = mpjSetorFuncionario;
        this.mpjSexoFuncionario = mpjSexoFuncionario;

    }

    @Id

    @Column(name = "mpj_cpfFuncionario", unique = true, nullable = false)
    public int getMpjCpfFuncionario() {
        return this.mpjCpfFuncionario;
    }

    public void setMpjCpfFuncionario(int mpjCpfFuncionario) {
        this.mpjCpfFuncionario = mpjCpfFuncionario;
    }

    @Column(name = "mpj_nomeCompletoFuncionario", nullable = false, length = 200)
    public String getMpjNomeCompletoFuncionario() {
        return this.mpjNomeCompletoFuncionario;
    }

    public void setMpjNomeCompletoFuncionario(String mpjNomeCompletoFuncionario) {
        this.mpjNomeCompletoFuncionario = mpjNomeCompletoFuncionario;
    }

    @Column(name = "mpj_telefoneFuncionario", length = 60)
    public String getMpjTelefoneFuncionario() {
        return this.mpjTelefoneFuncionario;
    }

    public void setMpjTelefoneFuncionario(String mpjTelefoneFuncionario) {
        this.mpjTelefoneFuncionario = mpjTelefoneFuncionario;
    }

    @Column(name = "mpj_emailFuncionario", length = 60)
    public String getMpjEmailFuncionario() {
        return this.mpjEmailFuncionario;
    }

    public void setMpjEmailFuncionario(String mpjEmailFuncionario) {
        this.mpjEmailFuncionario = mpjEmailFuncionario;
    }

    @Column(name = "mpj_cargoFuncionario", length = 60)
    public String getMpjCargoFuncionario() {
        return this.mpjCargoFuncionario;
    }

    public void setMpjCargoFuncionario(String mpjCargoFuncionario) {
        this.mpjCargoFuncionario = mpjCargoFuncionario;
    }

    @Column(name = "mpj_setorFuncionario", nullable = false, length = 40)
    public String getMpjSetorFuncionario() {
        return this.mpjSetorFuncionario;
    }

    public void setMpjSetorFuncionario(String mpjSetorFuncionario) {
        this.mpjSetorFuncionario = mpjSetorFuncionario;
    }

    @Column(name = "mpj_sexoFuncionario", nullable = false, length = 20)
    public String getMpjSexoFuncionario() {
        return this.mpjSexoFuncionario;
    }

    public void setMpjSexoFuncionario(String mpjSexoFuncionario) {
        this.mpjSexoFuncionario = mpjSexoFuncionario;
    }

}
